# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/lithium/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/lithium

PRODUCT_COPY_FILES += \
    vendor/xiaomi/lithium/proprietary/vendor/etc/camera/msm8996_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/msm8996_camera.xml \
    vendor/xiaomi/lithium/proprietary/vendor/etc/camera/ov16880_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov16880_chromatix.xml \
    vendor/xiaomi/lithium/proprietary/vendor/etc/camera/ov5675_primax_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov5675_primax_chromatix.xml \
    vendor/xiaomi/lithium/proprietary/vendor/etc/camera/s5k3p3_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p3_qtech_chromatix.xml \
    vendor/xiaomi/lithium/proprietary/vendor/firmware/tfa9891.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa9891.cnt \
    vendor/xiaomi/lithium/proprietary/vendor/etc/qdcm_calib_data_auo_fte716_1080p_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_auo_fte716_1080p_video_mode_dsi_panel.xml \
    vendor/xiaomi/lithium/proprietary/vendor/etc/qdcm_calib_data_sharp_fte716_1080p_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_sharp_fte716_1080p_video_mode_dsi_panel.xml \
    vendor/xiaomi/lithium/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/lithium/proprietary/vendor/etc/silence_short.wav:$(TARGET_COPY_OUT_VENDOR)/etc/silence_short.wav \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/Forte/Forte_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_General_cal.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/Forte/Forte_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Global_cal.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/Forte/Forte_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Handset_cal.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/Forte/Forte_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Headset_cal.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/Forte/Forte_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Speaker_cal.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/elliptic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/elliptic.xml \
    vendor/xiaomi/lithium/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/lithium/proprietary/vendor/firmware/a530_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b00 \
    vendor/xiaomi/lithium/proprietary/vendor/firmware/a530_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b01 \
    vendor/xiaomi/lithium/proprietary/vendor/firmware/a530_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b02 \
    vendor/xiaomi/lithium/proprietary/vendor/firmware/a530_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.elf \
    vendor/xiaomi/lithium/proprietary/vendor/firmware/a530_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.mdt

PRODUCT_PACKAGES += \
    libpn551_fw \
    libactuator_dw9763_a8_o-film \
    libactuator_dw9763_a8_qtech \
    libchromatix_ov16880_common \
    libchromatix_ov16880_cpp_hfr_120 \
    libchromatix_ov16880_cpp_hfr_60 \
    libchromatix_ov16880_cpp_hfr_90 \
    libchromatix_ov16880_cpp_liveshot \
    libchromatix_ov16880_cpp_preview \
    libchromatix_ov16880_cpp_snapshot \
    libchromatix_ov16880_cpp_video \
    libchromatix_ov16880_default_preview_3a \
    libchromatix_ov16880_default_video \
    libchromatix_ov16880_default_video_3a \
    libchromatix_ov16880_hfr_120 \
    libchromatix_ov16880_hfr_120_3a \
    libchromatix_ov16880_hfr_60 \
    libchromatix_ov16880_hfr_60_3a \
    libchromatix_ov16880_hfr_90 \
    libchromatix_ov16880_hfr_90_3a \
    libchromatix_ov16880_liveshot \
    libchromatix_ov16880_postproc \
    libchromatix_ov16880_preview \
    libchromatix_ov16880_snapshot \
    libchromatix_ov16880_zsl_preview_3a \
    libchromatix_ov16880_zsl_video_3a \
    libchromatix_ov5675_primax_a3_default_preview \
    libchromatix_ov5675_primax_a3_default_video \
    libchromatix_ov5675_primax_a3_hfr_120 \
    libchromatix_ov5675_primax_a3_hfr_60 \
    libchromatix_ov5675_primax_a3_hfr_90 \
    libchromatix_ov5675_primax_common \
    libchromatix_ov5675_primax_cpp_ds_chromatix \
    libchromatix_ov5675_primax_cpp_hfr_120 \
    libchromatix_ov5675_primax_cpp_hfr_60 \
    libchromatix_ov5675_primax_cpp_hfr_90 \
    libchromatix_ov5675_primax_cpp_liveshot \
    libchromatix_ov5675_primax_cpp_preview \
    libchromatix_ov5675_primax_cpp_snapshot \
    libchromatix_ov5675_primax_cpp_us_chromatix \
    libchromatix_ov5675_primax_cpp_video \
    libchromatix_ov5675_primax_cpp_video_full \
    libchromatix_ov5675_primax_default_video \
    libchromatix_ov5675_primax_hfr_120 \
    libchromatix_ov5675_primax_hfr_60 \
    libchromatix_ov5675_primax_hfr_90 \
    libchromatix_ov5675_primax_postproc \
    libchromatix_ov5675_primax_preview \
    libchromatix_ov5675_primax_snapshot \
    libchromatix_ov5675_primax_video_full \
    libchromatix_ov5675_primax_zsl_preview \
    libchromatix_ov5675_primax_zsl_video \
    libchromatix_s5k3p3_qtech_common \
    libchromatix_s5k3p3_qtech_cpp_hfr_120 \
    libchromatix_s5k3p3_qtech_cpp_hfr_60 \
    libchromatix_s5k3p3_qtech_cpp_hfr_90 \
    libchromatix_s5k3p3_qtech_cpp_liveshot \
    libchromatix_s5k3p3_qtech_cpp_preview \
    libchromatix_s5k3p3_qtech_cpp_snapshot \
    libchromatix_s5k3p3_qtech_cpp_video \
    libchromatix_s5k3p3_qtech_default_preview \
    libchromatix_s5k3p3_qtech_default_video \
    libchromatix_s5k3p3_qtech_hfr_120 \
    libchromatix_s5k3p3_qtech_hfr_120_3a \
    libchromatix_s5k3p3_qtech_hfr_60 \
    libchromatix_s5k3p3_qtech_hfr_60_3a \
    libchromatix_s5k3p3_qtech_hfr_90 \
    libchromatix_s5k3p3_qtech_hfr_90_3a \
    libchromatix_s5k3p3_qtech_liveshot \
    libchromatix_s5k3p3_qtech_postproc \
    libchromatix_s5k3p3_qtech_preview \
    libchromatix_s5k3p3_qtech_snapshot \
    libchromatix_s5k3p3_qtech_zsl_preview \
    libchromatix_s5k3p3_qtech_zsl_video \
    libmmcamera_ov16880 \
    libmmcamera_ov16880_ofilm_eeprom \
    libmmcamera_ov5675_primax \
    libmmcamera_s5k3p3_qtech \
    libmmcamera_s5k3p3_qtech_eeprom \
    libdirac-appi \
    fingerprint.fpc \
    sensors.elliptic
